### ISSUE TITLE
[Task] 관리자 페이지 기능 처리

### ISSUE THREAD

**Issue by kimdoyeonn** [codestates/rightnow#48]
### ISSUE
- Group: `client`
- Type: `feature`
- Detail: 관리자 페이지 서버 통신 처리

### TODO
- [ ] 신고 리스트(신고된 유저, 신고된 모임) 받아오기
- [ ] 모든 유저 리스트 받아오기
- [ ] 모든 모임 리스트 받아오기

### Estimated time
> Pick one

### Labels
- Estimated time: `E: 1.5h`
- Group : `client`
- Sprint: `Sprint 2`
- Urgency: `High`
