### ISSUE TITLE
[Task] 랜딩페이지 랜더링

### ISSUE THREAD

**Issue by JangSeBaRi** [codestates/rightnow#52]
### ISSUE
- Group: `client`
- Type: `feature`
- Detail: 랜딩페이지 틀 작업

### TODO
- [ ] 스크롤 다운 이벤트에 따른 css처리(애니메이션)
- [ ] 화면에 나타낼 설명 및 기능 정리
- [ ] 화면에 보여줄 이미지 선정

### Estimated time
> Pick one

### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `Sprint 2`
- Urgency: `Middle`
