### ISSUE TITLE
[Task] 랜딩페이지 기능처리

### ISSUE THREAD

**Issue by JangSeBaRi** [codestates/rightnow#56]
### ISSUE
- Group: `sr`
- Type: `feature`
- Detail: 랜딩페이지 기능처리

### TODO
- [ ] 로고 클릭시 랜딩페이지 화면으로 이동
- [ ] sign up 클릭 시 회원가입 페이지 이동
- [ ] sign in 클릭 시 로그인 페이지 이동
- [ ] 계정탈퇴 시 랜딩페이지로 이동될 때 alert 설계

### Estimated time
`1h`

### Labels
- Estimated time: `E: 1h`
- Group : `client`
- Sprint: `Sprint__2__`
- Urgency: `High`
