### ISSUE TITLE
[Task] 채팅 페이지 랜더링

### ISSUE THREAD

**Issue by kimdoyeonn** [codestates/rightnow#57]
### ISSUE
- Group: `client`
- Type: `feature`
- Detail: 채팅 페이지 디자인, 틀 작업

### TODO
- [x] 주고 받은 채팅
- [x] 모임에 참가중인 인원 리스트
- [ ] 모임에 대한 간단한 설명
- [ ] 상단에 공지사항

### Estimated time
> Pick one

### Labels
- Estimated time: `E: 2.5h`
- Group : `client`
- Sprint: `Sprint 2`
- Urgency: `High`
