### ISSUE TITLE
[Task] 마이페이지 기능 처리

### ISSUE THREAD

**Issue by kimdoyeonn** [codestates/rightnow#66]
### ISSUE
- Group: `client`
- Type: `feature`
- Detail: 마이페이지 기능 처리

### TODO
- [ ] 프로필 이미지 변경
- [ ] 프로필 닉네임 변경
- [ ] 비밀번호 변경(비밀번호 유효성 검사)
- [ ] 비밀번호 확인 후 계정 삭제

### Estimated time
> Pick one

### Labels
- Estimated time: `E: 2h`
- Group : `client`
- Sprint: `Sprint 3`
- Urgency: `High`
