### ISSUE TITLE
[Task] 회원가입 기능

### ISSUE THREAD

**Issue by JeongSubi** [codestates/rightnow#8]
### ISSUE
- Group: `server`, 
- Type: `feature`
- Detail: 회원가입 구현

### TODO
- [ ]  회원가입 요청 처리 함수 작성
- [ ]  nodemailer 이용한 이메일 인증
- [ ]  access token 발급해 쿠키에 저장
- [ ]   refresh token은 path 옵션이 있는 쿠키에 저장

### Estimated time
`2.5h`

### Labels
- Estimated time: `E: 2.5h`
- Group : `server`
- Sprint: `Sprint__2__`
- Urgency: `High`
